name: Publish engine

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    name: Publish engine for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
          - os: ubuntu-latest
            rid: linux-x64
          - os: macos-latest
            rid: osx-x64
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore
      working-directory: ./engine/Bomberjam
      run: dotnet restore

    - name: Publish
      working-directory: ./engine/Bomberjam
      run: dotnet publish -c Release -r ${{ matrix.rid }} -o ./dist/${{ matrix.rid }}/

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: bomberjam
        path: ./engine/Bomberjam/dist/