name: Publish engine on Linux x64

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      working-directory: ./engine/Bomberjam
      run: dotnet restore

    - name: Publish
      working-directory: ./engine/Bomberjam
      run: dotnet publish -c Release

    - name: Upload engine
      uses: actions/upload-artifact@v2
      with:
        name: engine-linux-x64
        path: ./engine/Bomberjam/bin/Release/net5.0/linux-x64/publish/bomberjam
