name: Website Docker Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the website Docker image
      run: docker build . --no-cache --file web.Dockerfile --tag bomberjam-website:$(date +%s)
