name: Worker Docker Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the worker Docker image
      run: docker build . --file worker.Dockerfile --tag bomberjam-worker:$(date +%s)
